-- USING 12345 AS A SEED TO THE RNG
/* QUERY 02 - STARBENCH - MINIMUM COST SUPPLIER QUERY  */
/* RETURN THE FIRST 100 SELECTED ROWS                                 */
/* VARIANT Q2.1 DECORELLATING  QUERY (MYSQL AND POSTGRESQL)           */
WITH T1(PARTKEY, MINCOST)  AS (
SELECT 
	P_PARTKEY,
	MIN(P_SUPPLYCOST) OVER (PARTITION BY P_PARTKEY)
FROM
	PART,
	SUPPLIER
WHERE
	P_SUPPKEY = S_SUPPKEY
	AND P_SIZE = 48
	AND P_TYPE LIKE '%TIN'
	AND S_REGION = 'AFRICA'
)
SELECT  /* DSS_02.SQL */
        S_ACCTBAL,
        S_NAME,
        S_NATION,
        P_PARTKEY,
        P_MFGR,
        S_ADDRESS,
        S_PHONE,
        S_COMMENT 
FROM 
	T1,
	PART,
        SUPPLIER
WHERE 
	P_PARTKEY=PARTKEY
	AND P_SUPPKEY=S_SUPPKEY
        AND P_SIZE = 48
        AND P_TYPE LIKE '%TIN'
        AND S_REGION = 'AFRICA'   
	AND P_SUPPLYCOST = MINCOST
ORDER BY
	S_ACCTBAL DESC,
        S_NATION,
        S_NAME,
        P_PARTKEY
LIMIT 100;

