-- USING 12345 AS A SEED TO THE RNG
/* QUERY 20 - STARBENCH - THE POTENTIAL PART PROMOTION QUERY */
WITH /* DSS_20.SQL */ T1 (PARTKEY,SUPP_NAME,SUPP_ADDRESS,QUANTITY) AS (
SELECT
	OD_PARTKEY, 
	S_NAME,
	S_ADDRESS,
	0.5 * SUM(OD_QUANTITY)
FROM 
	ORDER_DETAIL,
	SUPPLIER	
WHERE
	OD_SUPPKEY = S_SUPPKEY
	AND S_NATION = 'RUSSIA'
	AND OD_SHIPDATE >= '1994-01-01'
        AND OD_SHIPDATE <  DATE '1994-01-01' + INTERVAL '1' YEAR
GROUP BY 
	OD_PARTKEY, S_NAME, S_ADDRESS
)
SELECT  DISTINCT
        SUPP_NAME,
  	SUPP_ADDRESS
FROM
	T1,
        PART
WHERE
	T1.PARTKEY = P_PARTKEY
	AND P_NAME LIKE 'SLATE%'
	AND  P_AVAILQTY > T1.QUANTITY
ORDER BY
        SUPP_NAME
;

