/* Query 15 - Var_0 Rev_01 - TPC-H/TPC-R  Top Supplier Query */
WITH   /* dss_15.sql */ REVENUE (SUPPLIER_NO, TOTAL_REVENUE) AS (
SELECT
LO_SUPPKEY,
CAST(SUM(LO_EXTENDEDPRICE * (1-LO_DISCOUNT)) AS DECIMAL(18,2))
FROM
tpch.LINEORDER
WHERE
LO_SHIPDATE >= DATE '1996-01-01'
AND LO_SHIPDATE <  DATE '1996-01-01'+ INTERVAL '3' MONTH
GROUP BY
LO_SUPPKEY
)
SELECT 
DISTINCT S_SUPPKEY,
S_NAME,
S_ADDRESS,
S_PHONE,
TOTAL_REVENUE
FROM
tpch.SUPPLIER,
tpch.REVENUE
WHERE
S_SUPPKEY = SUPPLIER_NO
AND TOTAL_REVENUE = (
SELECT
MAX(TOTAL_REVENUE)
FROM
tpch.REVENUE
)
ORDER BY
S_SUPPKEY;

