-- USING DEFAULT SUBSTITUTIONS
/* QUERY 06 - STARBENCH - FORECASTING REVENUE CHANGE QUERY */
SELECT /* DSS_06.SQL */
        CAST(SUM(OD_EXTENDEDPRICE*OD_DISCOUNT) AS DECIMAL(18,2)) AS REVENUE
FROM 
        ssb2.ORDER_DETAIL
WHERE
        OD_SHIPDATE >= '1994-01-01'
        AND OD_SHIPDATE < DATE '1994-01-01' + INTERVAL '1' YEAR
        AND OD_DISCOUNT BETWEEN .06 - 0.01 AND .06 + 0.01
        AND OD_QUANTITY < 24;
