-- USING DEFAULT SUBSTITUTIONS
/* QUERY 15 - STARBENCH - TOP SUPPLIER QUERY */
WITH   /* DSS_15.SQL */ REVENUE (SUPPLIER_NO, TOTAL_REVENUE) AS (
SELECT
	OD_SUPPKEY,
	CAST(SUM(OD_EXTENDEDPRICE * (1-OD_DISCOUNT)) AS DECIMAL(18,2))
FROM
	ssb2.ORDER_DETAIL
WHERE
	OD_SHIPDATE >= DATE '1996-01-01'
	AND OD_SHIPDATE <  DATE '1996-01-01'+ INTERVAL '3' MONTH
GROUP BY
	OD_SUPPKEY
)
SELECT 
	DISTINCT S_SUPPKEY,
	S_NAME,
	S_ADDRESS,
	S_PHONE,
	TOTAL_REVENUE
FROM
	ssb2.SUPPLIER,
	REVENUE
WHERE
	S_SUPPKEY = SUPPLIER_NO
	AND TOTAL_REVENUE = (
		SELECT
			MAX(TOTAL_REVENUE)
		FROM
		REVENUE
		)
ORDER BY
	S_SUPPKEY;

