use ssb;

CREATE INDEX OD_IDX_PARTKEY ON ORDER_DETAIL(OD_PARTKEY);
CREATE INDEX OD_IDX_CUSTKEY ON ORDER_DETAIL(OD_CUSTKEY);
CREATE INDEX OD_IDX_ORDERKEY ON ORDER_DETAIL(OD_ORDERKEY);

CREATE UNIQUE INDEX IDX_CUST_CUSTKEY ON CUSTOMER(C_CUSTKEY);
CREATE INDEX IDX_CUST_REGION ON CUSTOMER(C_REGION);

CREATE INDEX IDX_PART_PARTKEY ON PART(P_PARTKEY);

CREATE INDEX IDX_SUPPLIER_REGION ON SUPPLIER(S_REGION);
CREATE INDEX IDX_SUPPLIER_NATION ON SUPPLIER (S_NATION);

