-- USING DEFAULT SUBSTITUTIONS
/* QUERY 14 - STARBENCH - PROMOTION EFFECT QUERY */
SELECT /* DSS_14.SQL */
        CAST(100.00*SUM(CASE 
                WHEN P_TYPE LIKE 'PROMO%'
                THEN OD_EXTENDEDPRICE*(1-OD_DISCOUNT) 
                ELSE 0 
        END ) / SUM(OD_EXTENDEDPRICE*(1-OD_DISCOUNT)) AS DECIMAL (18,2)) AS PROMO_REVENUE
FROM 
        ssb2.ORDER_DETAIL,
        ssb2.PART
WHERE
        OD_PARTKEY = P_PARTKEY
        AND OD_SHIPDATE >= '1995-09-01'
        AND OD_SHIPDATE < DATE '1995-09-01' + INTERVAL '1' MONTH;

