-- using default substitutions
/* Query 01 - Var_0 Rev_01 - TPC-H/TPC-R Pricing Summary Report Query   */

\timing
SELECT
        L_RETURNFLAG, 
        L_LINESTATUS,
        CAST(SUM(L_QUANTITY) AS DECIMAL(18,2)) AS SUM_QTY,
        CAST(SUM(L_EXTENDEDPRICE) AS DECIMAL(18,2)) AS SUM_BASE_PRICE,
        CAST(SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS DECIMAL(18,2)) AS SUM_DISC_PRICE,
        CAST(SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)*(1+L_TAX)) AS DECIMAL(18,2)) AS SUM_CHARGE,
        CAST(AVG(L_QUANTITY) AS DECIMAL(18,2)) AS AVG_QTY,
        CAST(AVG(L_EXTENDEDPRICE) AS DECIMAL(18,2)) AS AVG_PRICE,
        CAST(AVG(L_DISCOUNT) AS DECIMAL(18,2)) AS AVG_DISC,
        COUNT(*) AS COUNT_ORDER
FROM 
        tpch.LINEITEM
WHERE
        L_SHIPDATE <= DATE '1998-12-01' - INTERVAL '90' DAY
GROUP BY
        L_RETURNFLAG,
        L_LINESTATUS
ORDER BY
        L_RETURNFLAG,
        L_LINESTATUS;
\timing
