-- USING 12345 AS A SEED TO THE RNG


SELECT
	SUPP_NATION,
	CUST_NATION,
	L_YEAR,
	SUM(VOLUME) AS REVENUE
FROM
	(
		SELECT
			N1.N_NAME AS SUPP_NATION,
			N2.N_NAME AS CUST_NATION,
			EXTRACT(YEAR FROM L_SHIPDATE) AS L_YEAR,
			L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
		FROM
			tpch.SUPPLIER,
			tpch.LINEITEM,
			tpch.ORDERS,
			tpch.CUSTOMER,
			tpch.NATION N1,
			tpch.NATION N2
		WHERE
			S_SUPPKEY = L_SUPPKEY
			AND O_ORDERKEY = L_ORDERKEY
			AND C_CUSTKEY = O_CUSTKEY
			AND S_NATIONKEY = N1.N_NATIONKEY
			AND C_NATIONKEY = N2.N_NATIONKEY
			AND (
				(N1.N_NAME = 'KENYA' AND N2.N_NAME = 'RUSSIA')
				OR (N1.N_NAME = 'RUSSIA' AND N2.N_NAME = 'KENYA')
			)
			AND L_SHIPDATE BETWEEN DATE '1995-01-01' AND DATE '1996-12-31'
	) AS SHIPPING
GROUP BY
	SUPP_NATION,
	CUST_NATION,
	L_YEAR
ORDER BY
	SUPP_NATION,
	CUST_NATION,
	L_YEAR;
