-- USING 12345 AS A SEED TO THE RNG


SELECT
	O_YEAR,
	SUM(CASE
		WHEN NATION = 'RUSSIA' THEN VOLUME
		ELSE 0
	END) / SUM(VOLUME) AS MKT_SHARE
FROM
	(
		SELECT
			EXTRACT(YEAR FROM O_ORDERDATE) AS O_YEAR,
			L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME,
			N2.N_NAME AS NATION
		FROM
			tpch.PART,
			tpch.SUPPLIER,
			tpch.LINEITEM,
			tpch.ORDERS,
			tpch.CUSTOMER,
			tpch.NATION N1,
			tpch.NATION N2,
			tpch.REGION
		WHERE
			P_PARTKEY = L_PARTKEY
			AND S_SUPPKEY = L_SUPPKEY
			AND L_ORDERKEY = O_ORDERKEY
			AND O_CUSTKEY = C_CUSTKEY
			AND C_NATIONKEY = N1.N_NATIONKEY
			AND N1.N_REGIONKEY = R_REGIONKEY
			AND R_NAME = 'EUROPE'
			AND S_NATIONKEY = N2.N_NATIONKEY
			AND O_ORDERDATE BETWEEN DATE '1995-01-01' AND DATE '1996-12-31'
			AND P_TYPE = 'ECONOMY POLISHED BRASS'
	) AS ALL_NATIONS
GROUP BY
	O_YEAR
ORDER BY
	O_YEAR;
