-- USING 12345 AS A SEED TO THE RNG


SELECT
	P_BRAND,
	P_TYPE,
	P_SIZE,
	COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM
	tpch.PARTSUPP,
	tpch.PART
WHERE
	P_PARTKEY = PS_PARTKEY
	AND P_BRAND <> 'BRAND#21'
	AND P_TYPE NOT LIKE 'SMALL PLATED%'
	AND P_SIZE IN (9, 44, 13, 47, 15, 4, 48, 21)
	AND PS_SUPPKEY NOT IN (
		SELECT
			S_SUPPKEY
		FROM
			tpch.SUPPLIER
		WHERE
			S_COMMENT LIKE '%CUSTOMER%COMPLAINTS%'
	)
GROUP BY
	P_BRAND,
	P_TYPE,
	P_SIZE
ORDER BY
	SUPPLIER_CNT DESC,
	P_BRAND,
	P_TYPE,
	P_SIZE;
