-- USING 12345 AS A SEED TO THE RNG


SELECT
	SUM(L_EXTENDEDPRICE) / 7.0 AS AVG_YEARLY
FROM
	tpch.LINEITEM,
	tpch.PART
WHERE
	P_PARTKEY = L_PARTKEY
	AND P_BRAND = 'BRAND#12'
	AND P_CONTAINER = 'SM CAN'
	AND L_QUANTITY < (
		SELECT
			0.2 * AVG(L_QUANTITY)
		FROM
			tpch.LINEITEM
		WHERE
			L_PARTKEY = P_PARTKEY
	);
