-- using default substitutions
/* Query 20 - Var_0 Rev_01 - TPC-H/TPC-R The Potential Part Promotion query */
\timing
WITH T1 (PARTKEY, SUPPKEY, QUANTITY) AS (
	SELECT L_PARTKEY, L_SUPPKEY, 0.5 * SUM(L_QUANTITY)
	FROM tpch.LINEITEM
	WHERE L_SHIPDATE >= '1994-01-01'
	AND  L_SHIPDATE <  DATE '1994-01-01' + INTERVAL '1' YEAR
	GROUP BY L_PARTKEY, L_SUPPKEY
),
T2 (PARTKEY) AS (
	SELECT P_PARTKEY
	FROM tpch.PART
	WHERE P_NAME LIKE 'forest%'
)
SELECT
        S_NAME,
        S_ADDRESS
FROM
        T1,
        T2,
  	tpch.PARTSUPP,
        tpch.SUPPLIER,
        tpch.NATION
WHERE
	T1.PARTKEY = PS_PARTKEY
	AND T1.SUPPKEY = PS_SUPPKEY
	AND T1.SUPPKEY = S_SUPPKEY
	AND T2.PARTKEY = PS_PARTKEY
        AND PS_AVAILQTY > T1.QUANTITY
        AND S_NATIONKEY = N_NATIONKEY
        AND N_NAME = 'CANADA'
ORDER BY
        S_NAME
LIMIT 10;
\timing
