/* Query 01 - Var_0 Rev_01 - TPC-H/TPC-R Pricing Summary Report Query   */
SELECT /* dss_01.sql */
        LO_RETURNFLAG, 
        LO_LINESTATUS,
        CAST(SUM(LO_QUANTITY) AS DECIMAL(18,2)) AS SUM_QTY,
        CAST(SUM(LO_EXTENDEDPRICE) AS DECIMAL(18,2)) AS SUM_BASE_PRICE,
        CAST(SUM(LO_EXTENDEDPRICE*(1-LO_DISCOUNT)) AS DECIMAL(18,2)) AS SUM_DISC_PRICE,
        CAST(SUM(LO_EXTENDEDPRICE*(1-LO_DISCOUNT)*(1+LO_TAX)) AS DECIMAL(18,2)) AS SUM_CHARGE,
        CAST(AVG(LO_QUANTITY) AS DECIMAL(18,2)) AS AVG_QTY,
        CAST(AVG(LO_EXTENDEDPRICE) AS DECIMAL(18,2)) AS AVG_PRICE,
        CAST(AVG(LO_DISCOUNT) AS DECIMAL(18,2)) AS AVG_DISC,
        COUNT(*) AS COUNT_ORDER
FROM 
        LINEORDER
WHERE
        LO_SHIPDATE <= DATE '1998-12-01' - INTERVAL ':1' DAY
GROUP BY
        LO_RETURNFLAG,
        LO_LINESTATUS
ORDER BY
        LO_RETURNFLAG,
        LO_LINESTATUS;

