/* @(#)TERADATA 20.sql 1.1.1.1@(#) */
/* Query 20 - Var_0 Rev_01 - TPC-H/TPC-R The Potential Part Promotion query */
WITH /* dss_20.sql */ T1 (PARTKEY,SUPPKEY,QUANTITY) AS (
SELECT
	LO_PARTKEY, 
	LO_SUPPKEY,
	0.5 * SUM(LO_QUANTITY)
FROM 
	LINEORDER
WHERE
        LO_SHIPDATE >= ':2'
        AND  LO_SHIPDATE <  DATE ':2' + INTERVAL '1' YEAR
GROUP BY 
	LO_PARTKEY, LO_SUPPKEY
),
T2 (PARTKEY, SUPPKEY) AS (
SELECT P_PARTKEY, P_SUPPKEY
FROM
PART
WHERE
P_NAME LIKE ':1%'
)
SELECT 
        S_NAME,
  	S_ADDRESS
FROM
	T1,
 	T2,
        PART,
        SUPPLIER
WHERE
	T1.PARTKEY = P_PARTKEY
        AND  T1.SUPPKEY = S_SUPPKEY
	AND  T2.PARTKEY = P_PARTKEY
	AND  T2.SUPPKEY = S_SUPPKEY
        AND  P_SUPPKEY =  S_SUPPKEY
	AND  P_AVAILQTY > T1.QUANTITY
        AND  S_NATION = ':3'
ORDER BY
        S_NAME
;

