/* Query 20.1 - StarBench - The Potential Part Promotion query */
/* Decorellated version for MySQL and PostgreSQL               */
WITH T1 (PARTKEY,SUPP_NAME,SUPP_ADDRESS,QUANTITY) AS (
SELECT
	OD_PARTKEY, 
	S_NAME,
	S_ADDRESS,
	0.5 * SUM(OD_QUANTITY)
FROM 
	ORDER_DETAIL,
	SUPPLIER	
WHERE
	OD_SUPPKEY = S_SUPPKEY
	AND S_NATION = ':3'
	AND OD_SHIPDATE >= ':2'
        AND OD_SHIPDATE <  DATE ':2' + INTERVAL '1' YEAR
GROUP BY 
	OD_PARTKEY, S_NAME, S_ADDRESS
)
SELECT  DISTINCT
        SUPP_NAME,
  	SUPP_ADDRESS
FROM
	T1,
        PART
WHERE
	T1.PARTKEY = P_PARTKEY
--	AND  T1.SUPPKEY = P_SUPPKEY
	AND P_NAME LIKE ':1%'
	AND  P_AVAILQTY > T1.QUANTITY
ORDER BY
        SUPP_NAME
;

